### ISSUE TITLE
Cannot get Serilog logs into Prefix in ASP.NET Core 1 web application

### ISSUE THREAD

**Issue by salixzs** [jpknoll/Serilog.Sinks.Stackify#1]
ASP.NET Core Web (MVC) application. Stackify Prefix is installed.
Added NuGet packages for Serilog, Serilog.Sinks.Stackify and StackifyLib.

I can see events of MVC actions invoked normally in Prefix, even SQL Selects, but not logging statements from Serilog.
I can see those events in EventLog (another Sink) or in Trace (Serilog.Sinks.Trace), but still not in Prefix.

Here is appsettings.json which sets up Serilog and its sinks:

``` json
"Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Warning",
      "Microsoft": "Warning"
    }
  },
  "Serilog": {
    "Using": [ "Serilog.Sinks.Trace", "Serilog.Sinks.EventLog", "Serilog.Sinks.Stackify" ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "Stackify",
        "Args": {
          "restrictedToMinimumLevel": "Debug"
        }
      },
      {
        "Name": "Trace",
        "Args": {
          "restrictedToMinimumLevel": "Debug"
        }
      },
      {
        "Name": "EventLog",
        "Args": {
          "source": "MyApp",
          "restrictedToMinimumLevel": "Warning",
          "manageEventSource": true
        }
      }
    ],
    "Enrich": [ "FromLogContext" ],
    "Properties": {
      "Application": "MyApp"
    }
  }
```

What am I doing wrong?
Should I somehow try to add those app keys (using only Prefix)

``` xml
<add key="Stackify.AppName" value="My App Name" />
<add key="Stackify.Environment" value="" />
<add key="Stackify.ApiKey" value="" />
```

but how I can add them using appsettings.json?

**Comment by sporty81** [comment]
I've never tried configuring serilog from anything but code. So let me test it.

**Comment by salixzs** [comment]
After updating to latest StackifyLib (updated few days ago), problem disappeared - now I am getting Serilog records in Prefix, so I guess it can be closed.

**Comment by sporty81** [comment]
Oh yes it did require new StackifyLib
