### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by suddenelfilio** [jpknoll/Serilog.Sinks.Stackify#2]
Attempting to gather dependency information for package 'Serilog.Sinks.Stackify.1.23.3' with respect to project '', targeting '.NETFramework,Version=v4.6.2'
Gathering dependency information took 14,79 sec
Attempting to resolve dependencies for package 'Serilog.Sinks.Stackify.1.23.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Serilog.Sinks.Stackify.1.23.3'
Resolved actions to install package 'Serilog.Sinks.Stackify.1.23.3'
Retrieving package 'Serilog.Sinks.Stackify 1.23.3' from 'nuget.org'.
Adding package 'Serilog.Sinks.Stackify.1.23.3' to folder ''
Added package 'Serilog.Sinks.Stackify.1.23.3' to folder ''
Install failed. Rolling back...
Package 'Serilog.Sinks.Stackify.1.23.3 : Serilog [1.5.14, ), StackifyLib [1.23.3, )' does not exist in project ''
Removing package 'Serilog.Sinks.Stackify.1.23.3 : Serilog [1.5.14, ), StackifyLib [1.23.3, )' from folder ''
Removed package 'Serilog.Sinks.Stackify.1.23.3 : Serilog [1.5.14, ), StackifyLib [1.23.3, )' from folder ''
Executing nuget actions took 2,84 sec
**Failed to add reference. The package 'Serilog.Sinks.Stackify' tried to add a framework reference to 'System.IO' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.**

no 4.6.x support?

**Comment by sporty81** [comment]
Please try this pre-release version and see if you have the same issue

https://www.nuget.org/packages/Serilog.Sinks.Stackify/1.24.1-beta1

**Comment by suddenelfilio** [comment]
No sorry still the same message

![image](https://cloud.githubusercontent.com/assets/6460448/18827171/b63a720a-83d1-11e6-9c4c-8fad56d811f4.png)

**Comment by ngbrown** [comment]
I have the same issue on the newest package 1.25.2 and .Net Framework 4.6.1:

```
Attempting to gather dependency information for package 'Serilog.Sinks.Stackify.1.25.2' with respect to project 'Tis.WebService', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 4.23 sec
Attempting to resolve dependencies for package 'Serilog.Sinks.Stackify.1.25.2' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Serilog.Sinks.Stackify.1.25.2'
Resolved actions to install package 'Serilog.Sinks.Stackify.1.25.2'
Retrieving package 'StackifyLib 1.25.2' from 'nuget.org'.
Retrieving package 'Serilog.Sinks.Stackify 1.25.2' from 'nuget.org'.
Adding package 'StackifyLib.1.25.2' to folder '...\Tis.WebService\packages'
Added package 'StackifyLib.1.25.2' to folder '...\Tis.WebService\packages'
Added package 'StackifyLib.1.25.2' to 'packages.config'
Successfully installed 'StackifyLib 1.25.2' to Tis.WebService
Adding package 'Serilog.Sinks.Stackify.1.25.2' to folder '...\Tis.WebService\packages'
Added package 'Serilog.Sinks.Stackify.1.25.2' to folder '...\Tis.WebService\packages'
Install failed. Rolling back...
Package 'Serilog.Sinks.Stackify.1.25.2 : Serilog [1.5.14, ), StackifyLib [1.25.2, )' does not exist in project 'Tis.WebService'
Removed package 'StackifyLib.1.25.2 : Newtonsoft.Json [6.0.4, )' from 'packages.config'
Removing package 'Serilog.Sinks.Stackify.1.25.2 : Serilog [1.5.14, ), StackifyLib [1.25.2, )' from folder '...\Tis.WebService\packages'
Removed package 'Serilog.Sinks.Stackify.1.25.2 : Serilog [1.5.14, ), StackifyLib [1.25.2, )' from folder '...\Tis.WebService\packages'
Removing package 'StackifyLib.1.25.2 : Newtonsoft.Json [6.0.4, )' from folder '...\Tis.WebService\packages'
Removed package 'StackifyLib.1.25.2 : Newtonsoft.Json [6.0.4, )' from folder '...\Tis.WebService\packages'
Executing nuget actions took 3.36 sec
Failed to add reference. The package 'Serilog.Sinks.Stackify' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

```

**Comment by nicstrong** [comment]
ALso in 1.25.2:

Failed to add reference. The package 'Serilog.Sinks.Stackify' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

Could not locate the assembly "Serilog.Sinks.Stackify, Version=1.0.15.20398, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

**Comment by sturlath** [comment]
I really like the idea of this Prefix logging app but I really don´t like how slow the support for a critical error like this one is. I will probably not be moving to it if support takes 3-4 months...

**Comment by sturlath** [comment]
Ok I found out how I can do this manually.

For those that have the same problem you can unload your project and then edit it and add the following lines

    <Reference Include="System.IO" />
    <Reference Include="System.Linq" />
    <Reference Include="System.Runtime" />

You might not need them all but I did. Hopefully this will just be fixed in the package though.

**Comment by sporty81** [comment]
The issue should be resolved in the latest packages of StackifyLib and Serilog.Sinks.Stackify

**Comment by denys-olleik** [comment]
Doesn't work for me, same issues as op.

**Comment by BrianVallelunga** [comment]
I also can't install it. Same issue.

**Comment by sporty81** [comment]
Can you please try the newest package (2.0 beta2) and let me know if you are having an issue? Is your app ASP.NET, ASP.NET Core and which target framework version?

Install-Package Serilog.Sinks.Stackify -Pre

Thank you!

**Comment by plmaheu** [comment]
@sporty81 I have the same issue, running on ASP.NET MVC 5 on .NET 4.6.

Works like a charm with the sink v2.0.
